
[[constraint]]
  name = "github.com/Clever/leakybucket"
  version = "1.1.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.29.32"

[[constraint]]
  name = "github.com/pborman/uuid"

[[constraint]]
  name = "github.com/stretchr/testify"

[[constraint]]
  name = "gopkg.in/Clever/kayvee-go.v6"
  version = "6.24.0"

[[constraint]]
  name = "gopkg.in/tylerb/graceful.v1"
  version = "1.2.15"

[[constraint]]
  branch = "v1"
  name = "gopkg.in/yaml.v1"
